services:

  minio:
    image: minio/minio:latest
    container_name: sentinel-2-minio
    ports:
      - "9000:9000"    
      - "9001:9001"
    #volumes:
    #  - minio_data:/data
    volumes:
      - /Volumes/T7/Sentinel_Rasters/minio_data:/data
    command: server /data --console-address ":9001"
    user: "501:20"

#volumes:
#  minio_data:
#    driver: local