services:

  minio:
    image: minio/minio:latest
    container_name: prod-minio
    ports:
      - "9000:9000"    
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"


volumes:
  minio_data:
    driver: local